services:
  # Web service for the main application
  - type: web
    name: proinvest
    env: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: php -S 0.0.0.0:$PORT -t .
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: proinvest-db
          property: connectionString
      - key: CI_ENV
        value: production
      - key: APP_URL
        sync: false
      # Add other environment variables as needed
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false

# PostgreSQL database
databases:
  - name: proinvest-db
    plan: free
    postgresMajorVersion: 15
